<?php
/**
 * View -- of Application/IndexController/panel1Action
 * chophel@athang.com
 */
	$this->headTitle($title);
?>
<div class="page-header">
    <div class ="row">
		<div class ="col-lg-6">
			<h1> Welcome!  <b><?php echo $this->userObj->getColumn($this->author,'name'); ?></b></h1>
		</div>
	</div>
</div><!-- /.page-header -->

<div class="row">
	<div class="col-lg-12">
		<table class="table table-striped table-bordered table-hover" id="dataTables">
			
	</div>
</div>
</div>