<?php
/**
 * View -- of Application/IndexController/panel1Action
 * chophel@athang.com
 */
	$this->headTitle($title);
?>
<div class="page-header">
    <div class ="row">
		<div class ="col-lg-6">
			<h1>Admin Dashboard</h1>
		</div>
	</div>
</div><!-- /.page-header -->

<div class="row">
	<div class="col-lg-12">
		<table class="table table-striped table-bordered table-hover" id="dataTables">
			
	</div>
</div>
</div>
<hr>
<div class="row">
	<div class="col-lg-12">
		<?php foreach($this->menus as $menu):?>
			<div class="monal_dashboard_menu" >
				<div class="app_icon"  style="background-color:<?php echo $menu['color'];?>" data-url="<?php echo $this->url($menu['route']);?>" >
					<i class="<?php echo $menu['icon'];?> fa-3x"></i>
				</div>
				<div class="small">
					<?php echo $menu['menu'];?>
				</div>
			</div>
		<?php endforeach;?>
	</div>
</div>
<hr>
<script>
	$('.app_icon').each(function(){
		$(this).bind('click',function(){
			location.href=$(this).attr('data-url');
		});
	});
</script>